"""Automated remediation: dependency upgrades and self-healing code patches.

Two remediation layers live here:

1. **Dependency fixes** — for each vulnerable PyPI dependency, SGAI asks OSV.dev
   which versions fixed the advisories and upgrades the pin to a version that is
   safe against *all* of them. Lockfile ecosystems (npm/Go/Rust) are reported
   but not auto-rewritten yet.

2. **Code patches (self-healing)** — Bandit/Semgrep findings are mapped to
   AST-safe, line-targeted refactorings (``yaml.load`` → ``yaml.safe_load``,
   ``eval`` → ``ast.literal_eval``, ``shell=True`` → ``shlex.split``, …). Every
   patch is validated: the flagged line must actually contain the unsafe
   pattern, and the patched file must still parse. The :func:`heal` loop then
   runs the project's own tests via the sandboxed ``validate_patch`` MCP tool
   and rolls back any patch that breaks them.
"""

from __future__ import annotations

import ast
import difflib
import re
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path

import httpx
from packaging.version import InvalidVersion, Version

from sgai.config import HTTP_TIMEOUT, OSV_QUERY_BATCH_URL, OSV_QUERY_URL, is_skipped
from sgai.manifests import parse_manifest
from sgai.models import Finding



@dataclass
class Fix:
    """One proposed dependency upgrade."""

    file: str  # manifest path relative to the repo root
    package: str
    ecosystem: str
    old_version: str
    new_version: str

    @property
    def auto_fixable(self) -> bool:
        """True when SGAI can rewrite the manifest itself (requirements pins).

        Lockfiles (package-lock.json, uv.lock, Cargo.lock, …) must be
        regenerated by their own toolchain — a textual rewrite would break the
        integrity hashes — so those fixes ship as a command instead.
        """
        name = Path(self.file).name
        return name.startswith("requirements") and name.endswith(".txt")

    @property
    def command(self) -> str:
        """The toolchain command that applies this upgrade safely."""
        name, pkg, ver = Path(self.file).name, self.package, self.new_version
        if self.auto_fixable:
            return f"# rewritten in place: {pkg}=={ver}"
        if name == "package-lock.json":
            return f"npm install {pkg}@{ver}"
        if name == "go.mod":
            return f"go get {pkg}@v{ver} && go mod tidy"
        if name == "Cargo.lock":
            return f"cargo update -p {pkg} --precise {ver}"
        if name == "poetry.lock":
            return f"poetry update {pkg}"
        if name == "uv.lock":
            return f"uv lock --upgrade-package {pkg}"
        if name == "Pipfile.lock":
            return f"pipenv update {pkg}"
        return f"# bump {pkg} to >={ver} in {self.file} and re-lock"


async def resolve_patched_version(name: str, version: str, ecosystem: str = "PyPI") -> str | None:
    """Return the lowest safe upgrade for a vulnerable package, or ``None``.

    Collects every ``fixed`` version OSV advertises for this package (ignoring
    git-commit ranges, which aren't semantic versions) and returns the highest
    one — a version at or above it is patched against all the advisories.
    """
    async with httpx.AsyncClient(timeout=HTTP_TIMEOUT) as client:
        resp = await client.post(
            OSV_QUERY_URL, json={"version": version, "package": {"name": name, "ecosystem": ecosystem}}
        )
        resp.raise_for_status()
        data = resp.json()

    candidates: list[tuple[Version, str]] = []
    for vuln in data.get("vulns", []):
        for affected in vuln.get("affected", []):
            for rng in affected.get("ranges", []):
                if rng.get("type") not in ("ECOSYSTEM", "SEMVER"):
                    continue  # skip GIT commit-hash ranges
                for event in rng.get("events", []):
                    fixed = event.get("fixed")
                    if not fixed:
                        continue
                    try:
                        candidates.append((Version(fixed), fixed))
                    except InvalidVersion:
                        continue

    if not candidates:
        return None
    return max(candidates, key=lambda c: c[0])[1]


async def _vulnerable_packages(packages: list[dict]) -> list[dict]:
    """Filter ``packages`` down to those OSV knows a vulnerability for.

    One batch query per 100 packages, so a big lockfile costs a handful of
    requests instead of one per pin. On a batch failure every package stays a
    candidate — the per-package patch resolution then decides.
    """
    flagged: list[dict] = []
    async with httpx.AsyncClient(timeout=HTTP_TIMEOUT) as client:
        for start in range(0, len(packages), 100):
            chunk = packages[start : start + 100]
            queries = [
                {"version": p["version"], "package": {"name": p["name"], "ecosystem": p["ecosystem"]}}
                for p in chunk
            ]
            try:
                resp = await client.post(OSV_QUERY_BATCH_URL, json={"queries": queries})
                resp.raise_for_status()
                results = resp.json().get("results", [])
                flagged += [p for p, r in zip(chunk, results) if (r or {}).get("vulns")]
            except httpx.HTTPError:
                flagged += chunk
    return flagged


async def plan_fixes(repo_dir: str) -> list[Fix]:
    """Compute the upgrade plan for vulnerable pins under ``repo_dir``.

    Covers every manifest SGAI can audit (PyPI requirements/pyproject/lockfiles,
    npm, Go, crates.io). ``requirements*.txt`` pins are rewritten in place by
    :func:`apply_fixes`; lockfile upgrades are planned as toolchain commands
    (see :attr:`Fix.command`), because regenerating a lockfile by hand would
    break its integrity hashes.

    Manifests under test/example directories are left alone: those pins are
    fixtures (often intentionally vulnerable), not production dependencies.
    """
    from sgai.manifests import MANIFEST_GLOBS
    from sgai.risk import is_test_file

    root = Path(repo_dir).resolve()
    fixes: list[Fix] = []
    seen: set[tuple[str, str, str]] = set()  # (file, package, version)
    for glob in MANIFEST_GLOBS:
        for manifest in sorted(root.rglob(glob)):
            if is_skipped(manifest, root):
                continue
            rel = manifest.relative_to(root).as_posix()
            if is_test_file(rel):
                continue
            packages = parse_manifest(manifest)
            for pkg in await _vulnerable_packages(packages):
                key = (rel, pkg["name"], pkg["version"])
                if key in seen:
                    continue
                seen.add(key)
                patched = await resolve_patched_version(
                    pkg["name"], pkg["version"], pkg["ecosystem"]
                )
                if patched and patched != pkg["version"]:
                    fixes.append(
                        Fix(
                            file=rel,
                            package=pkg["name"],
                            ecosystem=pkg["ecosystem"],
                            old_version=pkg["version"],
                            new_version=patched,
                        )
                    )
    return fixes


def apply_fixes(repo_dir: str, fixes: list[Fix]) -> None:
    """Rewrite the manifests in place to apply the auto-fixable ``fixes``.

    Only ``requirements*.txt`` pins are rewritten; lockfile fixes carry a
    toolchain command instead (``Fix.command``) and are skipped here.
    """
    root = Path(repo_dir)
    by_file: dict[str, list[Fix]] = {}
    for fx in fixes:
        if not fx.auto_fixable:
            continue
        by_file.setdefault(fx.file, []).append(fx)

    for file, file_fixes in by_file.items():
        path = root / file
        text = path.read_text()
        for fx in file_fixes:
            text = text.replace(
                f"{fx.package}=={fx.old_version}", f"{fx.package}=={fx.new_version}"
            )
        path.write_text(text)


def build_pr_body(fixes: list[Fix]) -> str:
    """Render the pull-request body summarizing the upgrades."""
    lines = [
        "## SGAI automated dependency security fixes",
        "",
        "Upgrades known-vulnerable dependencies to patched versions:",
        "",
        "| Package | Ecosystem | File | From | To |",
        "|---|---|---|---|---|",
    ]
    for fx in fixes:
        lines.append(
            f"| `{fx.package}` | {fx.ecosystem} | `{fx.file}` "
            f"| {fx.old_version} | {fx.new_version} |"
        )
    manual = [fx for fx in fixes if not fx.auto_fixable]
    if manual:
        lines += [
            "",
            "### Lockfile upgrades (run these — lockfiles must be regenerated "
            "by their own toolchain)",
            "",
            "```sh",
            *[fx.command for fx in manual],
            "```",
        ]
    lines += ["", "_Patched versions resolved from OSV.dev advisories by SGAI._"]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Self-healing code patches
# --------------------------------------------------------------------------- #

@dataclass(frozen=True)
class PatchRule:
    """One unsafe-pattern → safe-pattern refactoring.

    ``rewrite`` transforms a single source line and returns ``None`` when the
    pattern is not present (the finding pointed somewhere this rule can't fix).
    ``needs_import`` names a stdlib module the patched line relies on; it is
    inserted once per file if not already imported.
    ``confidence`` (0.0–1.0) estimates how likely the rewrite is to preserve
    behavior; high-confidence patches are applied first so the rollback search
    discards the risky ones before the safe ones.
    """

    rule_id: str
    description: str
    rewrite: Callable[[str], str | None]
    needs_import: str | None = None
    confidence: float = 1.0


def _rewrite_yaml_load(line: str) -> str | None:
    """``yaml.load(x[, Loader=…])`` → ``yaml.safe_load(x)``."""
    with_loader = re.sub(
        r"yaml\.load\(\s*([^,()]+?)\s*,\s*Loader\s*=\s*[^)]+\)", r"yaml.safe_load(\1)", line
    )
    if with_loader != line:
        return with_loader
    plain = line.replace("yaml.load(", "yaml.safe_load(")
    return plain if plain != line else None


def _rewrite_eval(line: str) -> str | None:
    """Bare ``eval(x)`` → ``ast.literal_eval(x)`` (method calls are left alone)."""
    new = re.sub(r"(?<![\w.])eval\(", "ast.literal_eval(", line)
    return new if new != line else None


_SHELL_TRUE = re.compile(
    r"(?P<head>subprocess\.(?:call|run|Popen|check_call|check_output)\()"
    r"(?P<arg>[^,]+?),\s*shell\s*=\s*True"
)


def _rewrite_shell_true(line: str) -> str | None:
    """``subprocess.call(cmd, shell=True)`` → ``subprocess.call(shlex.split(cmd))``."""
    new = _SHELL_TRUE.sub(lambda m: f"{m.group('head')}shlex.split({m.group('arg').strip()})", line)
    return new if new != line else None


def _rewrite_weak_hash(line: str) -> str | None:
    """``hashlib.md5(`` / ``hashlib.sha1(`` → ``hashlib.sha256(``."""
    new = re.sub(r"hashlib\.(md5|sha1)\(", "hashlib.sha256(", line)
    return new if new != line else None


_HARDCODED_ASSIGN = re.compile(
    r"^(?P<indent>\s*)(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*(?P<q>['\"]).*(?P=q)\s*(?P<comment>#.*)?$"
)


def _rewrite_hardcoded_secret(line: str) -> str | None:
    """``TOKEN = "literal"`` → ``TOKEN = os.environ.get("TOKEN", "")``."""
    m = _HARDCODED_ASSIGN.match(line.rstrip("\n"))
    if not m:
        return None
    indent, name = m.group("indent"), m.group("name")
    comment = f"  {m.group('comment')}" if m.group("comment") else ""
    newline = "\n" if line.endswith("\n") else ""
    return f'{indent}{name} = os.environ.get("{name}", ""){comment}{newline}'


def _rewrite_verify_false(line: str) -> str | None:
    """``verify=False`` on requests calls → ``verify=True``."""
    new = re.sub(r"verify\s*=\s*False", "verify=True", line)
    return new if new != line else None


# Registry keyed by Bandit test id, with alias substrings so equivalent Semgrep
# check ids (e.g. "avoid-eval", "yaml-load") map onto the same refactoring.
_PATCH_RULES: dict[str, PatchRule] = {
    "B506": PatchRule(
        "B506", "Use yaml.safe_load() instead of yaml.load()", _rewrite_yaml_load,
        confidence=0.95,  # safe_load is a drop-in unless custom tags are parsed
    ),
    "B307": PatchRule(
        "B307", "Replace eval() with ast.literal_eval()", _rewrite_eval, needs_import="ast",
        confidence=0.55,  # literal_eval rejects names/expressions eval resolved
    ),
    "B602": PatchRule(
        "B602",
        "Drop shell=True; tokenize the command with shlex.split()",
        _rewrite_shell_true,
        needs_import="shlex",
        confidence=0.7,  # breaks commands that relied on shell features (pipes, globs)
    ),
    "B604": PatchRule(
        "B604",
        "Drop shell=True; tokenize the command with shlex.split()",
        _rewrite_shell_true,
        needs_import="shlex",
        confidence=0.7,
    ),
    "B303": PatchRule(
        "B303", "Replace weak hash with hashlib.sha256()", _rewrite_weak_hash,
        confidence=0.8,  # digests change length; stored-hash comparisons may break
    ),
    "B324": PatchRule(
        "B324", "Replace weak hash with hashlib.sha256()", _rewrite_weak_hash,
        confidence=0.8,
    ),
    "B105": PatchRule(
        "B105",
        "Move the hardcoded secret to an environment variable",
        _rewrite_hardcoded_secret,
        needs_import="os",
        confidence=0.6,  # runtime behavior depends on the env var being set
    ),
    "B501": PatchRule(
        "B501", "Re-enable TLS certificate verification", _rewrite_verify_false,
        confidence=0.9,  # only fails against endpoints with invalid certificates
    ),
}

# Semgrep check ids vary by ruleset; match them onto Bandit-equivalent rules by
# substring so the healer covers both scanners.
_RULE_ALIASES = [
    ("yaml", "B506"),
    ("eval", "B307"),
    ("shell", "B602"),
    ("md5", "B324"),
    ("sha1", "B324"),
    ("hardcoded", "B105"),
    ("verify", "B501"),
]


def _match_rule(finding_id: str) -> PatchRule | None:
    """Find the patch rule for a Bandit test id or a Semgrep check id."""
    rule = _PATCH_RULES.get(finding_id)
    if rule:
        return rule
    lowered = finding_id.lower()
    for needle, rule_id in _RULE_ALIASES:
        if needle in lowered:
            return _PATCH_RULES[rule_id]
    return None


@dataclass
class CodePatch:
    """One applied (or planned) line-level security refactoring."""

    file: str  # path relative to the repo root
    line: int  # 1-based line number of the finding
    rule: str
    description: str
    original_line: str
    patched_line: str
    confidence: float = 1.0  # from the PatchRule that produced it


@dataclass
class PatchPlan:
    """A set of validated patches plus the resulting file contents."""

    patches: list[CodePatch] = field(default_factory=list)
    originals: dict[str, str] = field(default_factory=dict)  # file → pre-patch content
    new_contents: dict[str, str] = field(default_factory=dict)  # file → post-patch content

    def diff(self, file: str) -> str:
        """Unified diff for one patched file."""
        return "".join(
            difflib.unified_diff(
                self.originals[file].splitlines(keepends=True),
                self.new_contents[file].splitlines(keepends=True),
                fromfile=f"a/{file}",
                tofile=f"b/{file}",
            )
        )


def _module_imported(tree: ast.Module, module: str) -> bool:
    for node in ast.walk(tree):
        if isinstance(node, ast.Import) and any(a.name.split(".")[0] == module for a in node.names):
            return True
        if isinstance(node, ast.ImportFrom) and (node.module or "").split(".")[0] == module:
            return True
    return False


def _insert_import(lines: list[str], module: str) -> list[str]:
    """Insert ``import <module>`` after the last top-level import (or the top)."""
    tree = ast.parse("".join(lines))
    last_import_line = 0
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            last_import_line = node.end_lineno or node.lineno
        else:
            break
    if last_import_line == 0 and tree.body and isinstance(tree.body[0], ast.Expr):
        first = tree.body[0]
        if isinstance(first.value, ast.Constant) and isinstance(first.value.value, str):
            last_import_line = first.end_lineno or first.lineno  # after the module docstring
    out = list(lines)
    out.insert(last_import_line, f"import {module}\n")
    return out


def _targets_from_findings(findings: list[Finding]) -> list[tuple[str, int, str]]:
    """Extract deduplicated ``(file, line, rule_id)`` patch targets from findings."""
    targets: list[tuple[str, int, str]] = []
    seen: set[tuple[str, int]] = set()
    for f in findings:
        if f.source not in ("static", "semgrep"):
            continue
        rule = _match_rule(f.id)
        if rule is None:
            continue
        file, _, line = f.location.rpartition(":")
        if not file or not line.isdigit():
            continue
        key = (file, int(line))
        if key in seen:
            continue  # Bandit and Semgrep often flag the same line
        seen.add(key)
        targets.append((file, int(line), rule.rule_id))
    # High-confidence rewrites first: the rollback search then discards the
    # risky, low-confidence patches before it ever questions the safe ones.
    targets.sort(key=lambda t: _PATCH_RULES[t[2]].confidence, reverse=True)
    return targets


def build_patch_plan(repo_dir: str, targets: list[tuple[str, int, str]]) -> PatchPlan:
    """Turn ``(file, line, rule_id)`` targets into a validated :class:`PatchPlan`.

    Each candidate patch must survive two AST checks before it is accepted:
    the file parses before the rewrite, and it still parses after. Patches
    that would break the file are silently skipped — healing must never make
    the code worse.
    """
    root = Path(repo_dir).resolve()
    plan = PatchPlan()

    by_file: dict[str, list[tuple[int, str]]] = {}
    for file, line, rule_id in targets:
        by_file.setdefault(file, []).append((line, rule_id))

    for file, file_targets in sorted(by_file.items()):
        path = root / file
        if not path.is_file():
            continue
        source = path.read_text()
        try:
            tree = ast.parse(source)
        except SyntaxError:
            continue  # never patch a file we can't parse

        lines = source.splitlines(keepends=True)
        needed_imports: set[str] = set()
        file_patches: list[CodePatch] = []

        for line_no, rule_id in sorted(file_targets):
            rule = _PATCH_RULES[rule_id]
            if not 1 <= line_no <= len(lines):
                continue
            original_line = lines[line_no - 1]
            patched_line = rule.rewrite(original_line)
            if patched_line is None or patched_line == original_line:
                continue
            candidate = list(lines)
            candidate[line_no - 1] = patched_line
            try:
                ast.parse("".join(candidate))
            except SyntaxError:
                continue  # the rewrite would break the file — reject it
            lines = candidate
            if rule.needs_import and not _module_imported(tree, rule.needs_import):
                needed_imports.add(rule.needs_import)
            file_patches.append(
                CodePatch(
                    file=file,
                    line=line_no,
                    rule=rule.rule_id,
                    description=rule.description,
                    original_line=original_line.rstrip("\n"),
                    patched_line=patched_line.rstrip("\n"),
                    confidence=rule.confidence,
                )
            )

        if not file_patches:
            continue
        for module in sorted(needed_imports):
            lines = _insert_import(lines, module)
        new_source = "".join(lines)
        try:
            ast.parse(new_source)
        except SyntaxError:
            continue  # import insertion should never break a file, but verify anyway
        plan.patches.extend(file_patches)
        plan.originals[file] = source
        plan.new_contents[file] = new_source

    return plan


def plan_code_patches(repo_dir: str, findings: list[Finding]) -> PatchPlan:
    """Map Bandit/Semgrep findings to a validated set of code patches."""
    return build_patch_plan(repo_dir, _targets_from_findings(findings))


def apply_patch_plan(repo_dir: str, plan: PatchPlan) -> None:
    """Write the patched file contents to disk."""
    root = Path(repo_dir).resolve()
    for file, content in plan.new_contents.items():
        (root / file).write_text(content)


def rollback_patch_plan(repo_dir: str, plan: PatchPlan) -> None:
    """Restore every patched file to its pre-patch content."""
    root = Path(repo_dir).resolve()
    for file, content in plan.originals.items():
        (root / file).write_text(content)


class DiffApplyError(Exception):
    """Raised when a unified diff does not apply cleanly to the target text."""


_HUNK_HEADER = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@")


def apply_unified_diff(original: str, diff: str) -> str:
    """Apply a unified diff to ``original`` and return the patched text.

    Strict by design: every context and deletion line must match the original
    exactly at the position the hunk header claims, otherwise
    :class:`DiffApplyError` is raised — a stale or hand-edited diff must never
    silently corrupt a file.
    """
    src = original.splitlines()
    out: list[str] = []
    pos = 0  # 0-based cursor into src

    hunks_seen = 0
    lines = diff.splitlines()
    i = 0
    while i < len(lines):
        header = _HUNK_HEADER.match(lines[i])
        if not header:
            i += 1
            continue
        hunks_seen += 1
        old_start = int(header.group(1))
        # An empty original file is addressed as line 0; clamp to keep 0-based math sane.
        hunk_pos = max(old_start - 1, 0)
        if hunk_pos < pos:
            raise DiffApplyError(f"hunk at line {old_start} overlaps a previous hunk")
        out.extend(src[pos:hunk_pos])
        pos = hunk_pos
        i += 1
        while i < len(lines) and not _HUNK_HEADER.match(lines[i]):
            line = lines[i]
            if line.startswith("\\"):  # "\ No newline at end of file"
                i += 1
                continue
            tag, body = line[:1], line[1:]
            if tag == " " or line == "":
                if pos >= len(src) or src[pos] != body:
                    raise DiffApplyError(f"context mismatch at original line {pos + 1}")
                out.append(body)
                pos += 1
            elif tag == "-":
                if pos >= len(src) or src[pos] != body:
                    raise DiffApplyError(f"deletion mismatch at original line {pos + 1}")
                pos += 1
            elif tag == "+":
                out.append(body)
            else:
                break  # not a hunk body line — end of this hunk
            i += 1

    if hunks_seen == 0:
        raise DiffApplyError("no @@ hunks found in the diff")
    out.extend(src[pos:])
    patched = "\n".join(out)
    if original.endswith("\n") or (not original and patched):
        patched += "\n"
    return patched


@dataclass
class HealResult:
    """Outcome of a self-healing run."""

    applied: list[CodePatch] = field(default_factory=list)
    rejected: list[CodePatch] = field(default_factory=list)  # rolled back: broke the tests
    plan: PatchPlan | None = None
    tests_ran: bool = False
    tests_passed: bool | None = None
    detail: str = ""


_Target = tuple[str, int, str]  # (file, line, rule_id)


def _bisect_breaking_targets(
    repo_dir: str,
    candidates: list[_Target],
    good: list[_Target],
    passes: Callable[[list[_Target]], bool],
) -> tuple[list[_Target], list[_Target]]:
    """Delta-debug the patch set: find the minimal breaking subset by bisection.

    Invariant: ``good`` is a patch set already known to pass the tests. Returns
    ``(kept, dropped)`` where ``kept ⊇ good`` passes and ``dropped`` is the
    minimal set of individually-blamed patches. Costs O(b·log n) test runs for
    b breaking patches among n, versus O(n) for one-at-a-time rollback.
    """
    if not candidates:
        return good, []
    if passes(good + candidates):
        return good + candidates, []
    if len(candidates) == 1:
        return good, candidates
    mid = len(candidates) // 2
    kept, dropped_left = _bisect_breaking_targets(repo_dir, candidates[:mid], good, passes)
    kept, dropped_right = _bisect_breaking_targets(repo_dir, candidates[mid:], kept, passes)
    return kept, dropped_left + dropped_right


async def heal(
    repo_dir: str,
    findings: list[Finding] | None = None,
    deep: bool = False,
    validate: bool = True,
) -> HealResult:
    """Self-heal ``repo_dir``: patch unsafe patterns, keep only test-passing patches.

    The loop: gather findings (unless provided), plan AST-safe patches, apply
    them, then run the project's test suite through the sandboxed
    ``validate_patch`` tool. If the tests fail, patches are rolled back one at a
    time — most recent first — re-running the tests after each rollback until
    they pass again. Patches that had to be reverted are reported in
    ``rejected`` so the developer can fix those spots manually.
    """
    from sgai.mcp_server import server

    if findings is None:
        from sgai.runner import gather_findings

        findings = await gather_findings(repo_dir, deep=deep)

    targets = _targets_from_findings(findings)
    plan = build_patch_plan(repo_dir, targets)
    if not plan.patches:
        return HealResult(detail="no patchable findings")

    if not validate:
        apply_patch_plan(repo_dir, plan)
        return HealResult(applied=plan.patches, plan=plan, detail="validation skipped")

    # Baseline: if the suite already fails before we touch anything, we can't
    # attribute failures to our patches — apply but report validation as moot.
    baseline = server.validate_patch(repo_dir)
    if not baseline.get("ran"):
        apply_patch_plan(repo_dir, plan)
        return HealResult(
            applied=plan.patches, plan=plan,
            detail=f"no test suite to validate against ({baseline.get('reason', 'unknown')})",
        )
    if not baseline.get("passed"):
        apply_patch_plan(repo_dir, plan)
        return HealResult(
            applied=plan.patches, plan=plan, tests_ran=True,
            detail="tests were already failing before healing; validation inconclusive",
        )

    apply_patch_plan(repo_dir, plan)
    result = server.validate_patch(repo_dir)
    if result.get("passed"):
        return HealResult(applied=plan.patches, plan=plan, tests_ran=True, tests_passed=True)

    # Binary-search rollback: delta-debug the target list to isolate the minimal
    # breaking subset instead of retracting patches one at a time. Targets are
    # already ordered by confidence, so risky patches are blamed first.
    rollback_patch_plan(repo_dir, plan)
    verdicts: dict[tuple[_Target, ...], bool] = {tuple(targets): False}  # full set: known red

    def _passes(subset: list[_Target]) -> bool:
        key = tuple(subset)
        if key in verdicts:
            return verdicts[key]
        subplan = build_patch_plan(repo_dir, subset)
        if not subplan.patches:
            verdicts[key] = True  # nothing applied — the baseline suite is green
            return True
        apply_patch_plan(repo_dir, subplan)
        outcome = bool(server.validate_patch(repo_dir).get("passed"))
        rollback_patch_plan(repo_dir, subplan)
        verdicts[key] = outcome
        return outcome

    kept, dropped = _bisect_breaking_targets(repo_dir, list(targets), [], _passes)

    all_patches = {(p.file, p.line): p for p in plan.patches}
    rejected = [all_patches[(f, ln)] for f, ln, _ in dropped if (f, ln) in all_patches]
    if not kept:
        return HealResult(
            rejected=list(plan.patches), tests_ran=True, tests_passed=False,
            detail="every patch combination broke the tests; all patches rolled back",
        )

    final_plan = build_patch_plan(repo_dir, kept)
    apply_patch_plan(repo_dir, final_plan)
    return HealResult(
        applied=final_plan.patches, rejected=rejected, plan=final_plan,
        tests_ran=True, tests_passed=True,
        detail=f"rolled back {len(rejected)} patch(es) that broke the tests "
               f"(isolated by binary search)",
    )
