"""Markdown security report generation for SGAI.

Turns a ranked list of :class:`~sgai.models.Finding` objects into a clean,
action-oriented Markdown report — the artifact a developer reads to fix things.
This is deterministic; the report agent can further narrate it, but the core
report stands on its own.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING

from sgai.models import Finding, Severity
from sgai.risk import severity_counts

if TYPE_CHECKING:
    from sgai.memory import ScanDiff

_SEVERITY_EMOJI = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH: "🟠",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🔵",
    Severity.UNKNOWN: "⚪",
}


def _changes_section(diff: "ScanDiff") -> list[str]:
    """Render the 'Changes since last scan' block from a memory diff."""
    lines = ["## Changes since last scan", ""]
    if diff.is_first_scan:
        lines += ["_First recorded scan of this target — establishing a baseline._", ""]
        return lines

    lines += [
        f"_Compared against the scan from {diff.previous_at}._",
        "",
        f"- 🆕 **New:** {len(diff.new)}",
        f"- ✅ **Fixed:** {len(diff.resolved)}",
        f"- ♻️ **Still open:** {len(diff.persisting)}",
    ]
    if diff.accepted:
        lines.append(f"- 🤝 **Accepted risks present:** {len(diff.accepted)}")
    lines.append("")

    if diff.new:
        lines += ["**Newly introduced:**", ""]
        for f in diff.new:
            lines.append(f"- {_SEVERITY_EMOJI[f.severity]} {f.id} — `{f.location}`")
        lines.append("")
    if diff.resolved:
        lines += ["**Fixed since last scan:**", ""]
        for meta in diff.resolved:
            lines.append(f"- {meta.get('id', '?')} — `{meta.get('location', '?')}`")
        lines.append("")
    return lines


def build_markdown_report(
    target: str,
    findings: list[Finding],
    generated_at: datetime | None = None,
    diff: "ScanDiff | None" = None,
) -> str:
    """Render a Markdown security report.

    Args:
        target: The audited path or repository, shown in the header.
        findings: Risk-ranked findings (highest first).
        generated_at: Timestamp for the report; defaults to now (UTC).
        diff: Optional change set vs. the previous recorded scan; when given, a
            "Changes since last scan" section is added.

    Returns:
        The full report as a Markdown string.
    """
    when = (generated_at or datetime.now(timezone.utc)).strftime("%Y-%m-%d %H:%M UTC")
    counts = severity_counts(findings)

    lines: list[str] = [
        "# SGAI Security Report",
        "",
        f"**Target:** `{target}`  ",
        f"**Generated:** {when}  ",
        f"**Total findings:** {len(findings)}",
        "",
        "## Summary",
        "",
    ]

    if not findings:
        lines += ["✅ No vulnerabilities found.", ""]
        if diff is not None:
            lines += _changes_section(diff)
        return "\n".join(lines)

    if diff is not None:
        lines += _changes_section(diff)

    lines += ["| Severity | Count |", "|---|---|"]
    for sev, count in counts.items():
        lines.append(f"| {_SEVERITY_EMOJI[sev]} {sev.label} | {count} |")
    lines += ["", "## Findings", "", "| # | Severity | Source | Location | Issue |", "|---|---|---|---|---|"]

    for i, f in enumerate(findings, 1):
        issue = f.title.replace("|", "\\|")
        lines.append(
            f"| {i} | {_SEVERITY_EMOJI[f.severity]} {f.severity.label} | {f.source} | `{f.location}` | {issue} |"
        )

    lines += ["", "## Remediation", ""]
    for i, f in enumerate(findings, 1):
        lines += [
            f"### {i}. {f.severity.label} — {f.id} ({f.location})",
            "",
            f"{f.detail}" if f.detail else "",
            f"**Fix:** {f.remediation}",
        ]
        if f.references:
            refs = ", ".join(f.references)
            lines.append(f"**Advisories:** {refs}")
        lines.append("")

    lines += [
        "---",
        "_Generated by SGAI — dependency data from OSV.dev, static analysis by Bandit._",
    ]
    return "\n".join(lines)
